// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class Tests;
@class TestsBuilder;
@class TestsTest;
@class TestsTest3G;
@class TestsTest3GBuilder;
@class TestsTest3GS;
@class TestsTest3GSBuilder;
@class TestsTest4;
@class TestsTest4Builder;
@class TestsTest4S;
@class TestsTest4SBuilder;
@class TestsTest5;
@class TestsTest5Builder;
@class TestsTest5S_5C;
@class TestsTest5S_5CBuilder;
@class TestsTestBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface TestModelRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Tests : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAge_:1;
  NSString* name;
  UInt32 age;
  NSMutableArray * testArray;
  NSMutableArray * test3GArray;
  NSMutableArray * test3GsArray;
  NSMutableArray * test4Array;
  NSMutableArray * test4SArray;
  NSMutableArray * test5Array;
  NSMutableArray * test5S5CArray;
}
- (BOOL) hasName;
- (BOOL) hasAge;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 age;
@property (readonly, strong) NSArray * test;
@property (readonly, strong) NSArray * test3G;
@property (readonly, strong) NSArray * test3Gs;
@property (readonly, strong) NSArray * test4;
@property (readonly, strong) NSArray * test4S;
@property (readonly, strong) NSArray * test5;
@property (readonly, strong) NSArray * test5S5C;
- (TestsTest*)testAtIndex:(NSUInteger)index;
- (TestsTest3G*)test3GAtIndex:(NSUInteger)index;
- (TestsTest3GS*)test3GsAtIndex:(NSUInteger)index;
- (TestsTest4*)test4AtIndex:(NSUInteger)index;
- (TestsTest4S*)test4SAtIndex:(NSUInteger)index;
- (TestsTest5*)test5AtIndex:(NSUInteger)index;
- (TestsTest5S_5C*)test5S5CAtIndex:(NSUInteger)index;

+ (Tests*) defaultInstance;
- (Tests*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestsBuilder*) builder;
+ (TestsBuilder*) builder;
+ (TestsBuilder*) builderWithPrototype:(Tests*) prototype;
- (TestsBuilder*) toBuilder;

+ (Tests*) parseFromData:(NSData*) data;
+ (Tests*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Tests*) parseFromInputStream:(NSInputStream*) input;
+ (Tests*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Tests*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Tests*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestsTest : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAge_:1;
  NSString* name;
  UInt32 age;
}
- (BOOL) hasName;
- (BOOL) hasAge;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 age;

+ (TestsTest*) defaultInstance;
- (TestsTest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestsTestBuilder*) builder;
+ (TestsTestBuilder*) builder;
+ (TestsTestBuilder*) builderWithPrototype:(TestsTest*) prototype;
- (TestsTestBuilder*) toBuilder;

+ (TestsTest*) parseFromData:(NSData*) data;
+ (TestsTest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest*) parseFromInputStream:(NSInputStream*) input;
+ (TestsTest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestsTest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestsTestBuilder : PBGeneratedMessageBuilder {
@private
  TestsTest* result;
}

- (TestsTest*) defaultInstance;

- (TestsTestBuilder*) clear;
- (TestsTestBuilder*) clone;

- (TestsTest*) build;
- (TestsTest*) buildPartial;

- (TestsTestBuilder*) mergeFrom:(TestsTest*) other;
- (TestsTestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestsTestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TestsTestBuilder*) setName:(NSString*) value;
- (TestsTestBuilder*) clearName;

- (BOOL) hasAge;
- (UInt32) age;
- (TestsTestBuilder*) setAge:(UInt32) value;
- (TestsTestBuilder*) clearAge;
@end

@interface TestsTest3G : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAge_:1;
  NSString* name;
  UInt32 age;
}
- (BOOL) hasName;
- (BOOL) hasAge;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 age;

+ (TestsTest3G*) defaultInstance;
- (TestsTest3G*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestsTest3GBuilder*) builder;
+ (TestsTest3GBuilder*) builder;
+ (TestsTest3GBuilder*) builderWithPrototype:(TestsTest3G*) prototype;
- (TestsTest3GBuilder*) toBuilder;

+ (TestsTest3G*) parseFromData:(NSData*) data;
+ (TestsTest3G*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest3G*) parseFromInputStream:(NSInputStream*) input;
+ (TestsTest3G*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest3G*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestsTest3G*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestsTest3GBuilder : PBGeneratedMessageBuilder {
@private
  TestsTest3G* result;
}

- (TestsTest3G*) defaultInstance;

- (TestsTest3GBuilder*) clear;
- (TestsTest3GBuilder*) clone;

- (TestsTest3G*) build;
- (TestsTest3G*) buildPartial;

- (TestsTest3GBuilder*) mergeFrom:(TestsTest3G*) other;
- (TestsTest3GBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestsTest3GBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TestsTest3GBuilder*) setName:(NSString*) value;
- (TestsTest3GBuilder*) clearName;

- (BOOL) hasAge;
- (UInt32) age;
- (TestsTest3GBuilder*) setAge:(UInt32) value;
- (TestsTest3GBuilder*) clearAge;
@end

@interface TestsTest3GS : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAge_:1;
  NSString* name;
  UInt32 age;
}
- (BOOL) hasName;
- (BOOL) hasAge;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 age;

+ (TestsTest3GS*) defaultInstance;
- (TestsTest3GS*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestsTest3GSBuilder*) builder;
+ (TestsTest3GSBuilder*) builder;
+ (TestsTest3GSBuilder*) builderWithPrototype:(TestsTest3GS*) prototype;
- (TestsTest3GSBuilder*) toBuilder;

+ (TestsTest3GS*) parseFromData:(NSData*) data;
+ (TestsTest3GS*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest3GS*) parseFromInputStream:(NSInputStream*) input;
+ (TestsTest3GS*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest3GS*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestsTest3GS*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestsTest3GSBuilder : PBGeneratedMessageBuilder {
@private
  TestsTest3GS* result;
}

- (TestsTest3GS*) defaultInstance;

- (TestsTest3GSBuilder*) clear;
- (TestsTest3GSBuilder*) clone;

- (TestsTest3GS*) build;
- (TestsTest3GS*) buildPartial;

- (TestsTest3GSBuilder*) mergeFrom:(TestsTest3GS*) other;
- (TestsTest3GSBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestsTest3GSBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TestsTest3GSBuilder*) setName:(NSString*) value;
- (TestsTest3GSBuilder*) clearName;

- (BOOL) hasAge;
- (UInt32) age;
- (TestsTest3GSBuilder*) setAge:(UInt32) value;
- (TestsTest3GSBuilder*) clearAge;
@end

@interface TestsTest4 : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAge_:1;
  NSString* name;
  UInt32 age;
}
- (BOOL) hasName;
- (BOOL) hasAge;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 age;

+ (TestsTest4*) defaultInstance;
- (TestsTest4*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestsTest4Builder*) builder;
+ (TestsTest4Builder*) builder;
+ (TestsTest4Builder*) builderWithPrototype:(TestsTest4*) prototype;
- (TestsTest4Builder*) toBuilder;

+ (TestsTest4*) parseFromData:(NSData*) data;
+ (TestsTest4*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest4*) parseFromInputStream:(NSInputStream*) input;
+ (TestsTest4*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest4*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestsTest4*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestsTest4Builder : PBGeneratedMessageBuilder {
@private
  TestsTest4* result;
}

- (TestsTest4*) defaultInstance;

- (TestsTest4Builder*) clear;
- (TestsTest4Builder*) clone;

- (TestsTest4*) build;
- (TestsTest4*) buildPartial;

- (TestsTest4Builder*) mergeFrom:(TestsTest4*) other;
- (TestsTest4Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestsTest4Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TestsTest4Builder*) setName:(NSString*) value;
- (TestsTest4Builder*) clearName;

- (BOOL) hasAge;
- (UInt32) age;
- (TestsTest4Builder*) setAge:(UInt32) value;
- (TestsTest4Builder*) clearAge;
@end

@interface TestsTest4S : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAge_:1;
  NSString* name;
  UInt32 age;
}
- (BOOL) hasName;
- (BOOL) hasAge;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 age;

+ (TestsTest4S*) defaultInstance;
- (TestsTest4S*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestsTest4SBuilder*) builder;
+ (TestsTest4SBuilder*) builder;
+ (TestsTest4SBuilder*) builderWithPrototype:(TestsTest4S*) prototype;
- (TestsTest4SBuilder*) toBuilder;

+ (TestsTest4S*) parseFromData:(NSData*) data;
+ (TestsTest4S*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest4S*) parseFromInputStream:(NSInputStream*) input;
+ (TestsTest4S*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest4S*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestsTest4S*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestsTest4SBuilder : PBGeneratedMessageBuilder {
@private
  TestsTest4S* result;
}

- (TestsTest4S*) defaultInstance;

- (TestsTest4SBuilder*) clear;
- (TestsTest4SBuilder*) clone;

- (TestsTest4S*) build;
- (TestsTest4S*) buildPartial;

- (TestsTest4SBuilder*) mergeFrom:(TestsTest4S*) other;
- (TestsTest4SBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestsTest4SBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TestsTest4SBuilder*) setName:(NSString*) value;
- (TestsTest4SBuilder*) clearName;

- (BOOL) hasAge;
- (UInt32) age;
- (TestsTest4SBuilder*) setAge:(UInt32) value;
- (TestsTest4SBuilder*) clearAge;
@end

@interface TestsTest5 : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAge_:1;
  NSString* name;
  UInt32 age;
}
- (BOOL) hasName;
- (BOOL) hasAge;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 age;

+ (TestsTest5*) defaultInstance;
- (TestsTest5*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestsTest5Builder*) builder;
+ (TestsTest5Builder*) builder;
+ (TestsTest5Builder*) builderWithPrototype:(TestsTest5*) prototype;
- (TestsTest5Builder*) toBuilder;

+ (TestsTest5*) parseFromData:(NSData*) data;
+ (TestsTest5*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest5*) parseFromInputStream:(NSInputStream*) input;
+ (TestsTest5*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest5*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestsTest5*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestsTest5Builder : PBGeneratedMessageBuilder {
@private
  TestsTest5* result;
}

- (TestsTest5*) defaultInstance;

- (TestsTest5Builder*) clear;
- (TestsTest5Builder*) clone;

- (TestsTest5*) build;
- (TestsTest5*) buildPartial;

- (TestsTest5Builder*) mergeFrom:(TestsTest5*) other;
- (TestsTest5Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestsTest5Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TestsTest5Builder*) setName:(NSString*) value;
- (TestsTest5Builder*) clearName;

- (BOOL) hasAge;
- (UInt32) age;
- (TestsTest5Builder*) setAge:(UInt32) value;
- (TestsTest5Builder*) clearAge;
@end

@interface TestsTest5S_5C : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasAge_:1;
  NSString* name;
  UInt32 age;
}
- (BOOL) hasName;
- (BOOL) hasAge;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 age;

+ (TestsTest5S_5C*) defaultInstance;
- (TestsTest5S_5C*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestsTest5S_5CBuilder*) builder;
+ (TestsTest5S_5CBuilder*) builder;
+ (TestsTest5S_5CBuilder*) builderWithPrototype:(TestsTest5S_5C*) prototype;
- (TestsTest5S_5CBuilder*) toBuilder;

+ (TestsTest5S_5C*) parseFromData:(NSData*) data;
+ (TestsTest5S_5C*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest5S_5C*) parseFromInputStream:(NSInputStream*) input;
+ (TestsTest5S_5C*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestsTest5S_5C*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestsTest5S_5C*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestsTest5S_5CBuilder : PBGeneratedMessageBuilder {
@private
  TestsTest5S_5C* result;
}

- (TestsTest5S_5C*) defaultInstance;

- (TestsTest5S_5CBuilder*) clear;
- (TestsTest5S_5CBuilder*) clone;

- (TestsTest5S_5C*) build;
- (TestsTest5S_5C*) buildPartial;

- (TestsTest5S_5CBuilder*) mergeFrom:(TestsTest5S_5C*) other;
- (TestsTest5S_5CBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestsTest5S_5CBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TestsTest5S_5CBuilder*) setName:(NSString*) value;
- (TestsTest5S_5CBuilder*) clearName;

- (BOOL) hasAge;
- (UInt32) age;
- (TestsTest5S_5CBuilder*) setAge:(UInt32) value;
- (TestsTest5S_5CBuilder*) clearAge;
@end

@interface TestsBuilder : PBGeneratedMessageBuilder {
@private
  Tests* result;
}

- (Tests*) defaultInstance;

- (TestsBuilder*) clear;
- (TestsBuilder*) clone;

- (Tests*) build;
- (Tests*) buildPartial;

- (TestsBuilder*) mergeFrom:(Tests*) other;
- (TestsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TestsBuilder*) setName:(NSString*) value;
- (TestsBuilder*) clearName;

- (BOOL) hasAge;
- (UInt32) age;
- (TestsBuilder*) setAge:(UInt32) value;
- (TestsBuilder*) clearAge;

- (NSMutableArray *)test;
- (TestsTest*)testAtIndex:(NSUInteger)index;
- (TestsBuilder *)addTest:(TestsTest*)value;
- (TestsBuilder *)setTestArray:(NSArray *)array;
- (TestsBuilder *)clearTest;

- (NSMutableArray *)test3G;
- (TestsTest3G*)test3GAtIndex:(NSUInteger)index;
- (TestsBuilder *)addTest3G:(TestsTest3G*)value;
- (TestsBuilder *)setTest3GArray:(NSArray *)array;
- (TestsBuilder *)clearTest3G;

- (NSMutableArray *)test3Gs;
- (TestsTest3GS*)test3GsAtIndex:(NSUInteger)index;
- (TestsBuilder *)addTest3Gs:(TestsTest3GS*)value;
- (TestsBuilder *)setTest3GsArray:(NSArray *)array;
- (TestsBuilder *)clearTest3Gs;

- (NSMutableArray *)test4;
- (TestsTest4*)test4AtIndex:(NSUInteger)index;
- (TestsBuilder *)addTest4:(TestsTest4*)value;
- (TestsBuilder *)setTest4Array:(NSArray *)array;
- (TestsBuilder *)clearTest4;

- (NSMutableArray *)test4S;
- (TestsTest4S*)test4SAtIndex:(NSUInteger)index;
- (TestsBuilder *)addTest4S:(TestsTest4S*)value;
- (TestsBuilder *)setTest4SArray:(NSArray *)array;
- (TestsBuilder *)clearTest4S;

- (NSMutableArray *)test5;
- (TestsTest5*)test5AtIndex:(NSUInteger)index;
- (TestsBuilder *)addTest5:(TestsTest5*)value;
- (TestsBuilder *)setTest5Array:(NSArray *)array;
- (TestsBuilder *)clearTest5;

- (NSMutableArray *)test5S5C;
- (TestsTest5S_5C*)test5S5CAtIndex:(NSUInteger)index;
- (TestsBuilder *)addTest5S5C:(TestsTest5S_5C*)value;
- (TestsBuilder *)setTest5S5CArray:(NSArray *)array;
- (TestsBuilder *)clearTest5S5C;
@end


// @@protoc_insertion_point(global_scope)
